### ISSUE TITLE
 Error in REST handler: `Invalid atomic update value for $__original_remove. Expected an object, received function`

### ISSUE THREAD

**Issue by mdhanda** [feathersjs/feathers-rest#59]
Same code was working fine before I updated some lib modules to their later versions. I believe, those libs were totally irrelevant to the code below. I am not sure whether this error belongs here or in some other module, but I am logging it here with below error logs pointing in feathers:rest module:

> feathers:rest REST handler calling `find` from `/auth/instagram` +19s
  feathers:rest REST handler calling `get` from `/auth/instagram/callback?code=acc66d95cd0f4bd49888f5153beb61a2&state=true` +987ms
  feathers-authentication:oauth2 Updating user: 575516a41764b5b4cd1fdd85 +2s
  feathers:rest Error in REST handler: `Invalid atomic update value for $__original_remove. Expected an object, received function` +5ms
  feathers-authentication:middleware An authentication error occurred. +6ms Error: Invalid atomic update value for $__original_remove. Expected an object, received function
    at Query._castUpdate (D:\Dev\workspace\WebstormProjects\ES6\angular2-esnext-starter\node_modules\mongoose\lib\query.js:2323:13)
    at Query.update (D:\Dev\workspace\WebstormProjects\ES6\angular2-esnext-starter\node_modules\mongoose\lib\query.js:2106:22)
    at Function.update (D:\Dev\workspace\WebstormProjects\ES6\angular2-esnext-starter\node_modules\mongoose\lib\model.js:2054:13)
    at Object.patch (D:\Dev\workspace\WebstormProjects\ES6\angular2-esnext-starter\node_modules\feathers-mongoose\lib\service.js:247:27)
    at D:\Dev\workspace\WebstormProjects\ES6\angular2-esnext-starter\node_modules\feathers-hooks\lib\hooks.js:74:31
    at new Promise (D:\Dev\workspace\WebstormProjects\ES6\angular2-esnext-starter\node_modules\core-js\modules\es6.promise.js:193:7)
    at D:\Dev\workspace\WebstormProjects\ES6\angular2-esnext-starter\node_modules\feathers-hooks\lib\hooks.js:58:16
    at run (D:\Dev\workspace\WebstormProjects\ES6\angular2-esnext-starter\node_modules\core-js\modules\es6.promise.js:89:22)
    at D:\Dev\workspace\WebstormProjects\ES6\angular2-esnext-starter\node_modules\core-js\modules\es6.promise.js:102:28
    at flush (D:\Dev\workspace\WebstormProjects\ES6\angular2-esnext-starter\node_modules\core-js\modules\_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)

Please guide me where I should look for answers.
Thanks.

**Comment by daffl** [comment]
This looks like a Mongoose error. Can you try and see if it works with the [toObject hook](http://docs.feathersjs.com/databases/mongoose.html#modifying-results-with-the-toobject-hook)?

**Comment by mdhanda** [comment]
Here is the output after applying the suggested hook:

`
 D:\Dev\workspace\WebstormProjects\ES6\angular2-esnext-starter\server\services\user\hooks\index.js:47
        hooks.toObject({}),
              ^

TypeError: hooks.toObject is not a function
    at Object.<anonymous> (D:\Dev\workspace\WebstormProjects\ES6\angular2-esnext-starter\server\services\user\hooks\index.js:47:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Dev\workspace\WebstormProjects\ES6\angular2-esnext-starter\server\services\user\index.js:5:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
`

**Comment by daffl** [comment]
Can you put up a breaking example to reproduce?

**Comment by mdhanda** [comment]
Looks like your suggestion is working and I was making an error putting it the right way. It confronted me while I was putting up the example.

```
const service = require('feathers-mongoose');
const hooks = require('feathers-hooks');
```
I was using 
`hooks.toObject({});`
instead of
`service.hooks.toObject({});
`

So, it works and feel free to close this issue.
Many thanks for your help.
